routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\AssetController;
use App\Http\Controllers\Dashboard\OfferController;
use App\Http\Controllers\Dashboard\ReportController;
use App\Http\Controllers\Dashboard\SettingController;
use Rap2hpoutre\LaravelLogViewer\LogViewerController;
use App\Http\Controllers\Dashboard\ActivityController;
use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\VerifiedAddressController;
use App\Http\Controllers\Dashboard\ForbiddenAddressController;

Route::prefix('dashboard')->middleware(['web', 'admin'])->name('dashboard.')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('index');
    Route::resource('/assets', AssetController::class);
    Route::resource('/offers', OfferController::class);
    Route::resource('/forbidden-addresses', ForbiddenAddressController::class);
    Route::resource('/verified-addresses', VerifiedAddressController::class);
    Route::resource('/activities', ActivityController::class);
    Route::resource('/reports', ReportController::class);
    Route::resource('/settings', SettingController::class);
    Route::resource('/categories', CategoryController::class);
    Route::get('logs', [LogViewerController::class, 'index'])->name('logs');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NftController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\VerificationController;

require __DIR__.'/dashboard.php';

Route::get('/', [HomeController::class, 'index'])->name('home');

require __DIR__.'/assets.php';

Route::get('/nft/create', [NftController::class, 'create'])->name('nfts.create');
Route::post('/nft/validate', [NftController::class, 'validateData'])->name('nfts.validate');
Route::get('/nft/{code}-{issuer}', [NftController::class, 'show'])->name('nfts.show');

Route::get('/files/{name}/restore', [FileController::class, 'restore'])->name('file.restore');
Route::post('/files/{name}/process', [FileController::class, 'upload'])->name('file.upload');
Route::delete('/files/{name}/process', [FileController::class, 'delete'])->name('file.delete');

Route::view('/faq', 'pages.faq')->name('pages.faq');
Route::view('/help', 'pages.help')->name('pages.help');
Route::view('/bounty-program', 'pages.bounty-program')->name('pages.bounty-program');
Route::get('/contact', [ContactController::class, 'index'])->name('pages.contact');
Route::post('/contact/submit', [ContactController::class, 'send'])->name('contact.submit');
Route::get('/verification', [VerificationController::class, 'index'])->name('pages.verification');
Route::post('/verification/submit', [VerificationController::class, 'send'])->name('verification.submit');

Route::get('/storage/asset-version-{id}/{file}', [FileController::class, 'show']);

require __DIR__.'/auth.php';

app/Models/File.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class File extends Model
{
    use HasFactory;

    protected $guarded = [];

    public $appends = ['url'];

    protected $casts = [
        'thumbnail' => 'array',
    ];

    public function getLocalUrlAttribute()
    {
        if(!empty($this->path)) {
            return Storage::disk('local')->url($this->path);
        }

        return '';
    }

    public function getCloudUrlAttribute()
    {
        if(!empty($this->object_path)) {
            return config('site.static_files_host').$this->object_path;
        }

        return '';
    }

    public function getUrlAttribute()
    {
        if(!empty($this->object_path)) {
            return config('site.static_files_host').$this->object_path;
        }

        return Storage::disk('local')->url($this->path);
    }

    public function thumb($size)
    {
        if(!empty($this->object_path)) {
            $url = config('site.static_files_host').$this->object_path;
            if(!empty($this->thumbnail) && isset($this->thumbnail[$size]) && strpos($url, '.gif') === false) {
                $url = config('site.static_files_host').$this->thumbnail[$size];
            }

            return $url;
        }

        return Storage::disk('local')->url($this->path);
    }
}

app/Http/Controllers/Dashboard/ActivityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Activity;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActivityController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $activities = Activity::latest()->paginate(10);

        return view('dashboard.activities.index', compact('activities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/AssetController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Asset;
use App\Helpers\AssetHelper;
use Illuminate\Http\Request;
use App\Jobs\Asset\ForceDelete;
use App\Http\Controllers\Controller;
use App\Jobs\Asset\UpdateSearchable;

class AssetController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $assets = Asset::latest()->paginate(10);

        return view('dashboard.assets.index', compact('assets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $asset = Asset::findOrFail($id);

        return view('dashboard.assets.edit', compact('asset'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $asset = Asset::findOrFail($id);

        $banned = $request->banned ? true : false;

        $nsfw = $request->nsfw ? true : false;

        if($asset->banned != $banned) {
            $asset->banned = $banned;

            $asset->save();

            AssetHelper::clearAssetCache($asset->code, $asset->issuer);    
        }

        if($asset->version->nsfw != $nsfw) {
            $asset->version->nsfw = $nsfw;

            $asset->version->save();

            AssetHelper::clearAssetCache($asset->code, $asset->issuer); 
            UpdateSearchable::dispatch($asset);  
        }

        return redirect()->back()->withSuccess('Asset successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $asset = Asset::findOrFail($id);

        ForceDelete::dispatch($asset);

        return redirect()->back()->withSuccess('The item queued for deletion!');
    }
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Helpers\MarketplaceHelper;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->paginate(50);

        return view('dashboard.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'sort' => ['required']
        ])->validate();

        $category = new Category;
        $category->name = $request->name;
        $category->icon = $request->icon;
        if($request->parent_id) $category->parent_id = $request->parent_id;
        $category->sort = $request->sort;
        $category->save();

        MarketplaceHelper::getCategories(false);

        return redirect()->route('dashboard.categories.index')->withSuccess('The category has been created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);

        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);

        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'sort' => ['required']
        ])->validate();

        $category->name = $request->name;
        $category->icon = $request->icon;
        if($request->parent_id) $category->parent_id = $request->parent_id;
        $category->sort = $request->sort;
        $category->save();

        MarketplaceHelper::getCategories(false);

        return redirect()->back()->withSuccess('Category successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        MarketplaceHelper::getCategories(false);

        return redirect()->back()->withSuccess('Category successfully deleted!');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    public function index()
    {
        return view('dashboard.index');
	}
}

app/Http/Controllers/Dashboard/FileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\MoveFileToObjectStorage;

class FileController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $files = File::latest()->paginate(10);

        return view('dashboard.files.index', compact('files'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function toCloud($id)
    {
        $file = File::findOrFail($id);

        MoveFileToObjectStorage::dispatch($file);
        
        return redirect()->back()->withSuccess('The file queued to be moved to clould!'); 
    }
}

app/Http/Controllers/Dashboard/ForbiddenAddressController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Models\ForbiddenAddress;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;

class ForbiddenAddressController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $addresses = ForbiddenAddress::latest()->paginate(10);

        return view('dashboard.forbidden-addresses.index', compact('addresses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.forbidden-addresses.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'address' => ['required', 'unique:forbidden_addresses,address']
        ])->validate();

        $forbiddenAddress = new ForbiddenAddress;
        $forbiddenAddress->address = $request->address;
        $forbiddenAddress->save();

        return redirect()->route('dashboard.forbidden-addresses.index')->withSuccess('The address has been added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $forbiddenAddress = ForbiddenAddress::findOrFail($id);

        $forbiddenAddress->delete();

        return redirect()->back()->withSuccess('The address has been deleted!');
    }
}

resources/views/dashboard/files/index.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <div class="container mx-auto sm:px-6 lg:px-8 py-6">
        <div class="hero-headline px-4 sm:text-center">
            <div class="sm:text-center">
                <h1 class="text-4xl tracking-tight font-thin text-purple-500 sm:text-5xl md:text-6xl">
                    <div class="block">Files</div>
                </h1>
                <p class="mt-3 text-sm text-gray-400 sm:max-w-xl sm:mx-auto">Files</p>
            </div>
        </div>

        <div class="mt-14 space-y-10">

            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200">
                                <thead class="bg-gray-50">
                                    <tr>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            File ID
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Type
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Local File
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Cloud File
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Thumbnails
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Created At
                                        </th>
                                        <th scope="col" class="relative px-6 py-3">
                                            <span class="sr-only">Actions</span>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @foreach($files as $file)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            {{ $file->id }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            {{ $file->type }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            @if($file->local_url)
                                            <a href="{{ $file->local_url }}" class="text-purple-500" target="new">View</a>
                                            @else
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                Empty
                                            </span>
                                            @endif
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            @if($file->cloud_url)
                                            <a href="{{ $file->cloud_url }}" class="text-purple-500" target="new">View</a>
                                            @else
                                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                Empty
                                            </span>
                                            @endif
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            @if(!empty($file->thumbnail))
                                                @foreach($file->thumbnail as $size => $value)
                                                <div>
                                                    <a href="{{ config('site.static_files_host').$value }}" class="font-medium text-purple-500" target="new">{{ $size }}</a>
                                                </div>
                                                @endforeach
                                            @endif
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ $file->created_at->diffForHumans() }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-4">
                                            @if(empty($file->cloud_url))
                                            <a onclick="if(confirm('Do you really want to move the file to the cloud?')) document.getElementById('fileToCloud{{ $file->id }}').submit();" href="javascript:;" class="text-red-500 hover:underline">To Cloud</a>
                                            <form id="fileToCloud{{ $file->id }}" action="{{ route('dashboard.files.to_cloud', $file->id) }}" method="POST">@csrf</form>
                                            @endif
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            {{ $files->links('dashboard.layouts.pagination') }}
        </div>
    </div>
@endsection