routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\AssetController;
use App\Http\Controllers\Dashboard\OfferController;
use App\Http\Controllers\Dashboard\ReportController;
use App\Http\Controllers\Dashboard\SettingController;
use Rap2hpoutre\LaravelLogViewer\LogViewerController;
use App\Http\Controllers\Dashboard\ActivityController;
use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\VerifiedAddressController;
use App\Http\Controllers\Dashboard\ForbiddenAddressController;

Route::prefix('dashboard')->middleware(['web', 'admin'])->name('dashboard.')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('index');
    Route::resource('/assets', AssetController::class);
    Route::resource('/offers', OfferController::class);
    Route::resource('/forbidden-addresses', ForbiddenAddressController::class);
    Route::resource('/verified-addresses', VerifiedAddressController::class);
    Route::resource('/activities', ActivityController::class);
    Route::resource('/reports', ReportController::class);
    Route::resource('/settings', SettingController::class);
    Route::resource('/categories', CategoryController::class);
    Route::get('logs', [LogViewerController::class, 'index'])->name('logs');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NftController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\VerificationController;

require __DIR__.'/dashboard.php';

Route::get('/', [HomeController::class, 'index'])->name('home');

require __DIR__.'/assets.php';

Route::get('/nft/create', [NftController::class, 'create'])->name('nfts.create');
Route::post('/nft/validate', [NftController::class, 'validateData'])->name('nfts.validate');
Route::get('/nft/{code}-{issuer}', [NftController::class, 'show'])->name('nfts.show');

Route::get('/files/{name}/restore', [FileController::class, 'restore'])->name('file.restore');
Route::post('/files/{name}/process', [FileController::class, 'upload'])->name('file.upload');
Route::delete('/files/{name}/process', [FileController::class, 'delete'])->name('file.delete');

Route::view('/faq', 'pages.faq')->name('pages.faq');
Route::view('/help', 'pages.help')->name('pages.help');
Route::view('/bounty-program', 'pages.bounty-program')->name('pages.bounty-program');
Route::get('/contact', [ContactController::class, 'index'])->name('pages.contact');
Route::post('/contact/submit', [ContactController::class, 'send'])->name('contact.submit');
Route::get('/verification', [VerificationController::class, 'index'])->name('pages.verification');
Route::post('/verification/submit', [VerificationController::class, 'send'])->name('verification.submit');

Route::get('/storage/asset-version-{id}/{file}', [FileController::class, 'show']);

require __DIR__.'/auth.php';

app/Models/Asset.php
<?php

namespace App\Models;

use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Asset extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $with = ['version'];

    protected $casts = [
        'banned' => 'boolean',
        'verified' => 'boolean',
        'dataentries' => 'array',
    ];

    public function getUrlAttribute()
    {
        return route('assets.show', ['code' => $this->code, 'issuer' => $this->issuer]);
    }

    public function getEditUrlAttribute()
    {
        return route('assets.edit', ['code' => $this->code, 'issuer' => $this->issuer]);
    }

    public function getUpdateUrlAttribute()
    {
        return route('assets.update', ['code' => $this->code, 'issuer' => $this->issuer]);
    }

    public function getDeleteUrlAttribute()
    {
        return route('assets.delete', ['code' => $this->code, 'issuer' => $this->issuer]);
    }

    public function getMakeOfferUrlAttribute()
    {
        return route('assets.make-offer', ['code' => $this->code, 'issuer' => $this->issuer]);
    }

    public function getOfferXdrUrlAttribute()
    {
        return route('assets.offer-xdr', ['code' => $this->code, 'issuer' => $this->issuer]);
    }

    public function getReportUrlAttribute()
    {
        return route('assets.report', ['code' => $this->code, 'issuer' => $this->issuer]);
    }

    public function version()
    {
        return $this->hasOne('App\Models\AssetVersion', 'id', 'asset_version_id');
    }

    public function offers()
    {
        return $this->hasMany('App\Models\Offer');
    }

    public function activities()
    {
        return $this->hasMany('App\Models\Activity');
    }

    protected static function booted()
    {
        static::created(function ($asset) {
            \App\Jobs\Asset\UpdateSearchable::dispatch($asset);
        });

        static::updated(function ($asset) {
            \App\Jobs\Asset\UpdateSearchable::dispatch($asset);
        });
    }
}

app/Http/Controllers/AssetController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\FileHelper;
use App\Models\Asset;
use App\Helpers\PythonHelper;
use App\Helpers\StellarHelper;
use App\Helpers\NFTHelper;
use App\Models\Searchable;
use App\Helpers\AssetHelper;
use App\Helpers\OfferHelper;
use App\Models\AssetVersion;
use Illuminate\Http\Request;
use App\Jobs\Asset\GetAuthor;
use App\Helpers\ActivityHelper;
use App\Jobs\Asset\ClearOffers;
use App\Models\ForbiddenAddress;
use App\Jobs\Asset\DeleteVersion;
use App\Helpers\MarketplaceHelper;
use App\Jobs\Asset\DeleteVersions;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Validator;
use App\Jobs\Activities\NewCreatedActivity;

class AssetController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'fetch', 'show']);
    }

    public function index()
    {
        return view('assets.index');
    }

    public function fetch(Request $request)
    {
        $limit = (int) $request->limit;
        
        if($limit > 100) $limit = 100;

        $searchQuery = $request->search;

        $searchFilter = (array) $request->filter;

        $category = $request->category;

        $searchOrder = (string) $request->order;

        $assetsSearch = Searchable::publicSearch()
                        ->search($searchQuery)
                        ->category($category)
                        ->filter($searchFilter)
                        ->orderResults($searchOrder)
                        ->paginate($limit);

        
        $assets = $assetsSearch->items();

        $assets = AssetHelper::fromSearchablesToList($assets);

        return [
            'currentPage' => $assetsSearch->currentPage(),
            'assets' => $assets,
            'ended' => $assetsSearch->hasMorePages() ? false : true,
            'total' => $assetsSearch->total()
        ];
    }

    public function show($code, $issuer)
    {
        $asset = Cache::rememberForever(AssetHelper::getCacheKey($code, $issuer), function() use ($code, $issuer) {
            $asset = Asset::where('code', $code)->where('issuer', $issuer)->firstOrFail();
            return $asset;
        });

        $asset->owner = NFTHelper::checkOwner($asset);

        if(!$asset->active) {
            AssetHelper::checkActive($asset);
        }

        $buyOffers = Cache::remember(OfferHelper::getCacheKey($asset->id, $asset->owner), 60, function() use ($asset) {
            return $asset->offers()->where('to', $asset->owner)->where('trade', 0)->orderByDesc('price')->get();
        });

        $activities = Cache::remember(ActivityHelper::getCacheKey($asset->id), 3600, function() use ($asset) {
            return $asset->activities()->orderByDesc('id')->get();
        });

        return view('assets.show', compact('asset', 'buyOffers', 'activities'));
    }

    public function add()
    {
        return view('assets.add');
    }

    public function store(Request $request)
    {
        $data = $request->all();

        $validator_array = [
            'code' => ['required'],
            'issuer' => ['required', function ($attribute, $value, $fail) {
                if (!StellarHelper::isValidAccountId($value)) {
                    $fail('Enter correct Stellar Address');
                }
            }],
            'price' => [
                'required', 
                'numeric',
                'min:0.01',
                'max:50000000000',
                'regex:/^\d+(\.\d{1,2})?$/'
            ],
            'min_offer' => [
                'required', 
                'numeric',
                'min:0.01',
                'max:50000000000',
                'regex:/^\d+(\.\d{1,2})?$/'
            ],
            'bounty' => [
                'nullable',
                'numeric',
                'min:0.01',
                'max:'.(config('site.maxBountyReward') * 100),
                'regex:/^\d+(\.\d{1,2})?$/'
            ],
            'name' => ['required', 'max:42', 'string'],
            'description' => ['required', 'max:2000', 'string'],
            'categories' => [function ($attribute, $value, $fail) {
                if(empty($value)) return true;
                if(!is_array($value)) $fail(__('An error has occurred, try again later.'));
                $categories = MarketplaceHelper::getCategoriesArray();
                foreach($value as $item) {
                    if(is_array($item) || !in_array($item,  $categories)) $fail(__('An error has occurred, try again later.'));
                }
            }],
            'terms' => ['required']
        ];

        $validator = Validator::make($request->all(), $validator_array, [
            'code.required' => 'An error occurred, please try again later.',
            'issuer.required' => 'NFT Asset Issuer is required.',

            'min_offer.numeric' => 'The amount must be a number.',
            'min_offer.min' => 'The amount must be at least :min.',
            'min_offer.max' => 'The amount may not be greater than :max.',
            'min_offer.regex' => 'The amount has incorrect format.',

            'price.numeric' => 'The price must be a number.',
            'price.min' => 'The price must be at least :min.',
            'price.max' => 'The price may not be greater than :max.',
            'price.regex' => 'The price has incorrect format.',

            'name.required' => 'The name is required.',
            'name.max' => 'The name may not be greater than :max characters.',
            'description.required' => 'The description is required.',
            'description.max' => 'The description may not be greater than :max characters.',

            'bounty.numeric' => 'The bounty must be a number.',
            'bounty.min' => 'The bounty must be at least :min.',
            'bounty.max' => 'The bounty may not be greater than :max.',
            'bounty.regex' => 'The bounty must be between 0.01 and '.(config('site.maxBountyReward') * 100),

            'terms.required' => 'You must agree to the terms.',
        ]);

        $validator->validate();

        $code = $request->code;

        $issuer = $request->issuer;

        $asset = AssetHelper::getAssetByCode($code, $issuer);

        if($asset) {
            $request->session()->flash('warning', 'The asset already exists');

            return ['success' => true, 'url' => $asset->url];
        }

        $forbiddenAddress = ForbiddenAddress::where('address', $issuer)->first();

        if(!empty($forbiddenAddress)) {
            return response()->json([
                'errors' => [
                    'issuer' => [__('You cannot use this asset, please choose a different one.')]
                ]
            ], 422);
        }

        $nft = NFTHelper::getNFT($code, $issuer);
        if($nft == false) {
            return response()->json([
                'errors' => [
                    'issuer' => [__('Selected asset is not an NFT')]
                ]
            ], 422);
        }

        $isOwner = NFTHelper::isNFTOwner($code, $issuer, session('publicKey'));
        if($isOwner == false) {
            return ['success' => false];
        }

        $keypair = PythonHelper::getKeypair();

        if($keypair == false) return ['success' => false];

        $assetVersion = new AssetVersion;
        $assetVersion->code = $nft['code'];
        $assetVersion->issuer = $nft['issuer'];
        $assetVersion->price = round($request->price * config('site.priceRatio'));
        $assetVersion->min_offer = round($request->min_offer * config('site.priceRatio'));
        $assetVersion->bounty = !empty($request->bounty) ? round($request->bounty / config('site.stroop')) : 0;
        $assetVersion->name = $request->name;
        $assetVersion->description = $request->description;
        $assetVersion->lockable = trim($request->lockable);
        $assetVersion->tradable = false;
        if(!empty($request->nsfw)) $assetVersion->nsfw = true;
        $assetVersion->private = false;
        if(!empty($request->private)) $assetVersion->private = true;
        $assetVersion->save();
        if(!empty($request->image)) {
            $assetVersion->image_id = FileHelper::getFileId($request->image, 'asset-version-'.$assetVersion->id);
            $assetVersion->save();
        }
        if(!empty($request->video)) {
            $assetVersion->video_id = FileHelper::getFileId($request->video, 'asset-version-'.$assetVersion->id, 'video');
            $assetVersion->save();
        }
        if(!empty($request->audio)) {
            $assetVersion->audio_id = FileHelper::getFileId($request->audio, 'asset-version-'.$assetVersion->id, 'audio');
            $assetVersion->save();
        }
        $assetVersion->categories()->sync((array) $request->categories);

        $asset = new Asset;
        $asset->asset_version_id = $assetVersion->id;
        $asset->owner = session('publicKey');
        $asset->code = $nft['code'];
        $asset->issuer = $nft['issuer'];
        $asset->escrow_public_key = $keypair['public'];
        $asset->escrow_secret_key = $keypair['secret'];
        $asset->dataentries = $nft['dataentries'];
        $asset->home_domain = $nft['home_domain'];
        $asset->save();

        GetAuthor::dispatch($asset);

        NewCreatedActivity::dispatch($asset, [
            'from' => $asset->owner
        ]);

        return ['success' => true, 'url' => $asset->url];
    }

    public function edit($code, $issuer)
    {
        $asset = Cache::rememberForever(AssetHelper::getCacheKey($code, $issuer), function() use ($code, $issuer) {
            $asset = Asset::where('code', $code)->where('issuer', $issuer)->firstOrFail();
            return $asset;
        });

        if(!$asset->active) {
            return redirect($asset->url)->withDanger('The item needs to be activated.');
        }

        if($asset->owner != session('publicKey')) {

app/Http/Controllers/Dashboard/ActivityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Activity;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActivityController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $activities = Activity::latest()->paginate(10);

        return view('dashboard.activities.index', compact('activities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    public function index()
    {
        return view('dashboard.index');
	}
}

resources/views/dashboard/assets/edit.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <div class="container mx-auto sm:px-6 lg:px-8 py-6">
        <div class="hero-headline px-4 sm:text-center">
            <div class="sm:text-center">
                <h1 class="text-4xl tracking-tight font-thin text-purple-500 sm:text-5xl md:text-6xl">
                    <div class="block">Assets</div>
                </h1>
                <p class="mt-3 text-sm text-gray-400 sm:max-w-xl sm:mx-auto">Asset Edit</p>
            </div>
        </div>

        <div class="mt-14 space-y-10">

            <div class="relative w-full mt-6 p-6 bg-white dark:bg-gray-700 shadow overflow-hidden sm:rounded-lg">
                <div class="space-y-4 mb-12">
                    <div>
                        <div class="font-medium">Tradable:</div> 
                        <div class="text-sm">{{ $asset->version->tradable ? 'Yes' : 'No' }}</div>
                    </div>
                    <div>
                        <div class="font-medium">Price:</div> 
                        <div class="text-sm">{{ formatPrice($asset->version->price) }}</div>
                    </div>
                    <div>
                        <div class="font-medium">Min Offer:</div> 
                        <div class="text-sm">{{ formatPrice($asset->version->min_offer) }}</div>
                    </div>
                    <div>
                        <div class="font-medium">Name:</div> 
                        <div class="text-sm">{{ $asset->version->name }}</div>
                    </div>
                    <div>
                        <div class="font-medium">Lockable:</div> 
                        <div class="text-sm">{{ $asset->version->lockable }}</div>
                    </div>
                    <div>
                        <div class="font-medium">Escrow:</div> 
                        <div class="text-sm">{{ $asset->escrow_public_key }} ({{ $asset->escrow_secret_key }})</div>
                    </div>
                </div>

                <form action="{{ route('dashboard.assets.update', $asset->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="space-y-6">
                        <div>
                            <div class="flex items-start">
                                <div class="flex items-center h-5">
                                    <input id="banned" name="banned" type="checkbox" value="1" @if($asset->banned == 1) checked @endif class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                                </div>
                                <div class="ml-3 text-sm">
                                    <label for="banned" class="font-medium text-gray-700">Banned</label>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="flex items-start">
                                <div class="flex items-center h-5">
                                    <input id="nsfw" name="nsfw" type="checkbox" value="1" @if($asset->version->nsfw == 1) checked @endif class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                                </div>
                                <div class="ml-3 text-sm">
                                    <label for="nsfw" class="font-medium text-gray-700">NSFW</label>
                                </div>
                            </div>
                        </div>
                        <div>
                            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-purple-500 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
                                Update Asset
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
@endsection

resources/views/dashboard/assets/index.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <div class="container mx-auto sm:px-6 lg:px-8 py-6">
        <div class="hero-headline px-4 sm:text-center">
            <div class="sm:text-center">
                <h1 class="text-4xl tracking-tight font-thin text-purple-500 sm:text-5xl md:text-6xl">
                    <div class="block">Assets</div>
                </h1>
                <p class="mt-3 text-sm text-gray-400 sm:max-w-xl sm:mx-auto">Asset List</p>
            </div>
        </div>

        <div class="mt-14 space-y-10">

            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200">
                                <thead class="bg-gray-50">
                                    <tr>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Asset ID
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            NFT
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Active
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Banned
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            NSFW
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Private
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Lockable
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Created At
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Updated At
                                        </th>
                                        <th scope="col" class="relative px-6 py-3">
                                            <span class="sr-only">Actions</span>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @foreach($assets as $asset)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            {{ $asset->id }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            <a href="{{ $asset->url }}" class="text-purple-500" target="new">{{ $asset->code }}</a>
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            @if($asset->active)
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                    Yes
                                                </span>
                                            @else
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                    No
                                                </span>
                                            @endif
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            @if($asset->banned)
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                    Yes
                                                </span>
                                            @else
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                    No
                                                </span>
                                            @endif
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            @if(!$asset->version->nsfw)
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                    No
                                                </span>
                                            @else
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                    Yes
                                                </span>
                                            @endif
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            @if($asset->version->private)
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                    Yes
                                                </span>
                                            @else
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                    No
                                                </span>
                                            @endif
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            @if($asset->version->lockable)
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                    Yes
                                                </span>
                                            @else
                                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                                    No
                                                </span>
                                            @endif
                                        </td>

                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ $asset->created_at->diffForHumans() }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ $asset->updated_at->diffForHumans() }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-4">
                                            <a href="{{ route('dashboard.assets.edit', $asset->id) }}" class="text-purple-500 hover:underline">Edit</a>
                                            <a onclick="if(confirm('Do you really want to delete the asset?')) document.getElementById('assetDelete{{ $asset->id }}').submit();" href="javascript:;" class="text-red-500 hover:underline">Delete</a>
                                            <form id="assetDelete{{ $asset->id }}" action="{{ route('dashboard.assets.destroy', $asset->id) }}" method="POST">@csrf @method('DELETE')</form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            {{ $assets->links('dashboard.layouts.pagination') }}
        </div>
    </div>
@endsection