routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Dashboard\AssetController;
use App\Http\Controllers\Dashboard\OfferController;
use App\Http\Controllers\Dashboard\ReportController;
use App\Http\Controllers\Dashboard\SettingController;
use Rap2hpoutre\LaravelLogViewer\LogViewerController;
use App\Http\Controllers\Dashboard\ActivityController;
use App\Http\Controllers\Dashboard\CategoryController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\VerifiedAddressController;
use App\Http\Controllers\Dashboard\ForbiddenAddressController;

Route::prefix('dashboard')->middleware(['web', 'admin'])->name('dashboard.')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('index');
    Route::resource('/assets', AssetController::class);
    Route::resource('/offers', OfferController::class);
    Route::resource('/forbidden-addresses', ForbiddenAddressController::class);
    Route::resource('/verified-addresses', VerifiedAddressController::class);
    Route::resource('/activities', ActivityController::class);
    Route::resource('/reports', ReportController::class);
    Route::resource('/settings', SettingController::class);
    Route::resource('/categories', CategoryController::class);
    Route::get('logs', [LogViewerController::class, 'index'])->name('logs');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NftController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\VerificationController;

require __DIR__.'/dashboard.php';

Route::get('/', [HomeController::class, 'index'])->name('home');

require __DIR__.'/assets.php';

Route::get('/nft/create', [NftController::class, 'create'])->name('nfts.create');
Route::post('/nft/validate', [NftController::class, 'validateData'])->name('nfts.validate');
Route::get('/nft/{code}-{issuer}', [NftController::class, 'show'])->name('nfts.show');

Route::get('/files/{name}/restore', [FileController::class, 'restore'])->name('file.restore');
Route::post('/files/{name}/process', [FileController::class, 'upload'])->name('file.upload');
Route::delete('/files/{name}/process', [FileController::class, 'delete'])->name('file.delete');

Route::view('/faq', 'pages.faq')->name('pages.faq');
Route::view('/help', 'pages.help')->name('pages.help');
Route::view('/bounty-program', 'pages.bounty-program')->name('pages.bounty-program');
Route::get('/contact', [ContactController::class, 'index'])->name('pages.contact');
Route::post('/contact/submit', [ContactController::class, 'send'])->name('contact.submit');
Route::get('/verification', [VerificationController::class, 'index'])->name('pages.verification');
Route::post('/verification/submit', [VerificationController::class, 'send'])->name('verification.submit');

Route::get('/storage/asset-version-{id}/{file}', [FileController::class, 'show']);

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function asset_versions()
    {
        return $this->belongsToMany('App\Models\AssetVersion');
    }
}

app/Http/Controllers/Dashboard/ActivityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Activity;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ActivityController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $activities = Activity::latest()->paginate(10);

        return view('dashboard.activities.index', compact('activities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/AssetController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Asset;
use App\Helpers\AssetHelper;
use Illuminate\Http\Request;
use App\Jobs\Asset\ForceDelete;
use App\Http\Controllers\Controller;
use App\Jobs\Asset\UpdateSearchable;

class AssetController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $assets = Asset::latest()->paginate(10);

        return view('dashboard.assets.index', compact('assets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $asset = Asset::findOrFail($id);

        return view('dashboard.assets.edit', compact('asset'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $asset = Asset::findOrFail($id);

        $banned = $request->banned ? true : false;

        $nsfw = $request->nsfw ? true : false;

        if($asset->banned != $banned) {
            $asset->banned = $banned;

            $asset->save();

            AssetHelper::clearAssetCache($asset->code, $asset->issuer);    
        }

        if($asset->version->nsfw != $nsfw) {
            $asset->version->nsfw = $nsfw;

            $asset->version->save();

            AssetHelper::clearAssetCache($asset->code, $asset->issuer); 
            UpdateSearchable::dispatch($asset);  
        }

        return redirect()->back()->withSuccess('Asset successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $asset = Asset::findOrFail($id);

        ForceDelete::dispatch($asset);

        return redirect()->back()->withSuccess('The item queued for deletion!');
    }
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Helpers\MarketplaceHelper;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->paginate(50);

        return view('dashboard.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'sort' => ['required']
        ])->validate();

        $category = new Category;
        $category->name = $request->name;
        $category->icon = $request->icon;
        if($request->parent_id) $category->parent_id = $request->parent_id;
        $category->sort = $request->sort;
        $category->save();

        MarketplaceHelper::getCategories(false);

        return redirect()->route('dashboard.categories.index')->withSuccess('The category has been created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);

        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view('dashboard.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);

        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'sort' => ['required']
        ])->validate();

        $category->name = $request->name;
        $category->icon = $request->icon;
        if($request->parent_id) $category->parent_id = $request->parent_id;
        $category->sort = $request->sort;
        $category->save();

        MarketplaceHelper::getCategories(false);

        return redirect()->back()->withSuccess('Category successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        MarketplaceHelper::getCategories(false);

        return redirect()->back()->withSuccess('Category successfully deleted!');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    public function index()
    {
        return view('dashboard.index');
	}
}

app/Http/Controllers/Dashboard/FileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Jobs\MoveFileToObjectStorage;

class FileController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $files = File::latest()->paginate(10);

        return view('dashboard.files.index', compact('files'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function toCloud($id)
    {
        $file = File::findOrFail($id);

        MoveFileToObjectStorage::dispatch($file);
        
        return redirect()->back()->withSuccess('The file queued to be moved to clould!'); 
    }
}

app/Http/Controllers/Dashboard/ForbiddenAddressController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Models\ForbiddenAddress;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;

class ForbiddenAddressController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $addresses = ForbiddenAddress::latest()->paginate(10);

        return view('dashboard.forbidden-addresses.index', compact('addresses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.forbidden-addresses.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'address' => ['required', 'unique:forbidden_addresses,address']
        ])->validate();

        $forbiddenAddress = new ForbiddenAddress;
        $forbiddenAddress->address = $request->address;
        $forbiddenAddress->save();

        return redirect()->route('dashboard.forbidden-addresses.index')->withSuccess('The address has been added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $forbiddenAddress = ForbiddenAddress::findOrFail($id);

        $forbiddenAddress->delete();

        return redirect()->back()->withSuccess('The address has been deleted!');
    }
}

resources/views/dashboard/categories/create.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <div class="container mx-auto sm:px-6 lg:px-8 py-6">
        <div class="hero-headline px-4 sm:text-center">
            <div class="sm:text-center">
                <h1 class="text-4xl tracking-tight font-thin text-purple-500 sm:text-5xl md:text-6xl">
                    <div class="block">Categories</div>
                </h1>
                <p class="mt-3 text-sm text-gray-400 sm:max-w-xl sm:mx-auto">Category Add</p>
            </div>
        </div>

        <div class="mt-14 space-y-10">

            <div class="relative w-full mt-6 p-6 bg-white dark:bg-gray-700 shadow overflow-hidden sm:rounded-lg">
                <form action="{{ route('dashboard.categories.store') }}" method="POST">
                    @csrf
                    <div class="space-y-6">
                        <div>
                            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
                            <input type="text" name="name" id="name" value="{{ old('name') }}" class="mt-1 focus:ring-purple-500 focus:border-purple-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            @error('name')
                            <p class="mt-2 text-sm text-red-600 validation-error">{{ $message }}</p>
                            @endif
                        </div>
                        <div>
                            <label for="parent_id" class="block text-sm font-medium text-gray-700">Parent ID</label>
                            <input type="text" name="parent_id" id="parent_id" value="{{ old('parent_id') }}" class="mt-1 focus:ring-purple-500 focus:border-purple-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            @error('parent_id')
                            <p class="mt-2 text-sm text-red-600 validation-error">{{ $message }}</p>
                            @endif
                        </div>
                        <div>
                            <label for="icon" class="block text-sm font-medium text-gray-700">Icon</label>
                            <input type="text" name="icon" id="icon" value="{{ old('icon') }}" class="mt-1 focus:ring-purple-500 focus:border-purple-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            @error('icon')
                            <p class="mt-2 text-sm text-red-600 validation-error">{{ $message }}</p>
                            @endif
                        </div>
                        <div>
                            <label for="sort" class="block text-sm font-medium text-gray-700">Sort</label>
                            <input type="text" name="sort" id="sort" value="{{ old('sort') }}" class="mt-1 focus:ring-purple-500 focus:border-purple-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            @error('sort')
                            <p class="mt-2 text-sm text-red-600 validation-error">{{ $message }}</p>
                            @endif
                        </div>
                        <div>
                            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-purple-500 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
                                Add Category
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
@endsection

resources/views/dashboard/categories/edit.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <div class="container mx-auto sm:px-6 lg:px-8 py-6">
        <div class="hero-headline px-4 sm:text-center">
            <div class="sm:text-center">
                <h1 class="text-4xl tracking-tight font-thin text-purple-500 sm:text-5xl md:text-6xl">
                    <div class="block">Categories</div>
                </h1>
                <p class="mt-3 text-sm text-gray-400 sm:max-w-xl sm:mx-auto">Category Edit</p>
            </div>
        </div>

        <div class="mt-14 space-y-10">

            <div class="relative w-full mt-6 p-6 bg-white dark:bg-gray-700 shadow overflow-hidden sm:rounded-lg">
                <form action="{{ route('dashboard.categories.update', $category->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="space-y-6">
                        <div>
                            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
                            <input type="text" name="name" id="name" value="{{ old('name', $category->name) }}" class="mt-1 focus:ring-purple-500 focus:border-purple-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            @error('name')
                            <p class="mt-2 text-sm text-red-600 validation-error">{{ $message }}</p>
                            @endif
                        </div>
                        <div>
                            <label for="parent_id" class="block text-sm font-medium text-gray-700">Parent ID</label>
                            <input type="text" name="parent_id" id="parent_id" value="{{ old('parent_id', $category->parent_id) }}" class="mt-1 focus:ring-purple-500 focus:border-purple-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            @error('parent_id')
                            <p class="mt-2 text-sm text-red-600 validation-error">{{ $message }}</p>
                            @endif
                        </div>
                        <div>
                            <label for="icon" class="block text-sm font-medium text-gray-700">Icon</label>
                            <input type="text" name="icon" id="icon" value="{{ old('icon', $category->icon) }}" class="mt-1 focus:ring-purple-500 focus:border-purple-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            @error('icon')
                            <p class="mt-2 text-sm text-red-600 validation-error">{{ $message }}</p>
                            @endif
                        </div>
                        <div>
                            <label for="sort" class="block text-sm font-medium text-gray-700">Sort</label>
                            <input type="text" name="sort" id="sort" value="{{ old('sort', $category->sort) }}" class="mt-1 focus:ring-purple-500 focus:border-purple-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            @error('sort')
                            <p class="mt-2 text-sm text-red-600 validation-error">{{ $message }}</p>
                            @endif
                        </div>
                        <div>
                            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-purple-500 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
                                Update Category
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
@endsection

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <div class="container mx-auto sm:px-6 lg:px-8 py-6">
        <div class="hero-headline px-4 sm:text-center">
            <div class="sm:text-center">
                <h1 class="text-4xl tracking-tight font-thin text-purple-500 sm:text-5xl md:text-6xl">
                    <div class="block">Categories</div>
                </h1>
                <p class="mt-3 text-sm text-gray-400 sm:max-w-xl sm:mx-auto">Categories List</p>
            </div>
            <div class="mt-6">
                <a href="{{ route('dashboard.categories.create') }}" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-purple-500 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">
                    Add Category
                </a>
            </div>
        </div>

        <div class="mt-14 space-y-10">

            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200">
                                <thead class="bg-gray-50">
                                    <tr>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Categrory ID
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Parent ID
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Name
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Icon
                                        </th>
                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                            Sort
                                        </th>
                                        <th scope="col" class="relative px-6 py-3">
                                            <span class="sr-only">Actions</span>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                    @foreach($categories as $category)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            {{ $category->id }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            {{ $category->parent_id }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            {{ $category->name }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            {{ $category->icon }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm">
                                            {{ $category->sort }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium space-x-4">
                                            <a href="{{ route('dashboard.categories.edit', $category->id) }}" class="text-purple-500 hover:underline">Edit</a>
                                            <a onclick="if(confirm('Do you really want to delete the category?')) document.getElementById('categoryDelete{{ $category->id }}').submit();" href="javascript:;" class="text-red-500 hover:underline">Delete</a>
                                            <form id="categoryDelete{{ $category->id }}" action="{{ route('dashboard.categories.destroy', $category->id) }}" method="POST">@csrf @method('DELETE')</form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            {{ $categories->links('dashboard.layouts.pagination') }}
        </div>
    </div>
@endsection